In [4]:
# 패키지 불러오기
from selenium import webdriver
import pandas as pd

driver = webdriver.Chrome()

# 검색어 입력 및 검색
keyword = '가산동 맛집'
food_map_search_url = f"https://map.kakao.com/?q={keyword}"

driver.get(food_map_search_url)
driver.get(food_map_search_url)

In [5]:
ind = 1  # 현재 복사한 순서
no = 1  # 1~5페이지 중 위치한 곳
page = 1  # 현재 페이지 번호
list1 = []  # 결과물이 저장되는 리스트

while 1:
    try:
        # 업체명, 주소, 평점
        title = driver.find_element(by='xpath',value = f'//*[@id="info.search.place.list"]/li[{ind}]/div[3]/strong/a[2]').text
        addr = driver.find_element(by='xpath',value = f'//*[@id="info.search.place.list"]/li[{ind}]/div[5]/div[2]/p[1]').text
        score = driver.find_element(by='xpath',value = f'//*[@id="info.search.place.list"]/li[{ind}]/div[4]/span[1]/em').text
        list1.append([title, addr, score])
        
        ind += 1
        
    except:
        # 더보기 버튼 찾기
        if driver.find_element(by='xpath',value = f'//*[@id="info.search.place.more"]').is_displayed():
            driver.find_element(by='xpath',value = f'//*[@id="info.search.place.more"]').click()
            no += 1
            ind = 1
            page += 1
            continue

        # 다음 페이지로 이동
        elif no >= 5:
            driver.find_element(by='xpath',value = f'//*[@id="info.search.page.next"]').click()
            no = 1
            ind = 1
            page += 1
            continue
            
        # 5페이지 단위마다 다음 페이지 버튼 누르기
        elif driver.find_element(by='xpath',value = f'//*[@id="info.search.page.no{no+1}"]').is_displayed():
            no += 1
            driver.find_element(by='xpath',value = f'//*[@id="info.search.page.no{no}"]').click()
            ind = 1
            page += 1
            continue
        
        # 더이상 이동할수 없을 경우 종료
        else:
            break

In [6]:
food = pd.DataFrame(list1)

#열 이름 바꾸기
food.columns = ['상호명', '주소', '평점']

In [21]:
#평점 높은 순으로 보기
rank = food.sort_values(['평점'], ascending=False)

#평점순서대로 순위 매기기
rank['순위'] = range(1, len(rank) + 1)

#['순위'] 열이 앞으로 오도록
rank = rank[['순위', '상호명', '주소', '평점']]

rank

      순위              상호명                                      주소   평점
244    1              꾸움당                     서울 금천구 남부순환로112길 52  5.0
281    2             스시긴가                   서울 금천구 가산디지털1로 100 2층  5.0
90     3          동남집 독산점       서울 금천구 가산디지털1로 25 대륭테크노타운17차 104호  5.0
242    4          돼지네연탄구이                      서울 금천구 가산로9길 12 1층  5.0
257    5           다원전통찻집    서울 금천구 디지털로9길 32 갑을그레이트밸리 지상1층 A113호  5.0
..   ...              ...                                     ...  ...
67   316    두껍삼 가산디지털단지역점  서울 금천구 가산디지털1로 168 우림라이온스밸리 A동 2층 219호
277  317          따봉수제돈까스       서울 금천구 디지털로9길 32 갑을그레이트밸리 2층 218호
50   318               육로        서울 금천구 벚꽃로 298 대륭포스트타워6차 1층 102호
159  319  79파운야드 가산디지털단지점       서울 금천구 벚꽃로 298 대륭포스트타워 6차 1층 101호
318  320   두꺼비식당 현대아울렛가산점                     서울 금천구 디지털로10길 9 7층

[320 rows x 4 columns]